### ISSUE TITLE
Share Link issues

### ISSUE THREAD

**Issue by youkha** [ncbi/icn3d#10]
Here are a couple of simple examples where you'd like share link to work

this is a simple script - get the interactions between 2 chains (hopefully domains when we get that level and even lower at the SSE level) highlight on 3D and display "schematics" (labels) colored with some property such as charge for example (down the road also an array of distances between the labels - showing the interactions) and SHARE the link ...

https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?showseq=1&mmdbid=1kzq&buidx=1&command=select%20interaction%201KZQ_A,1KZQ_B;%20select%20interaction%201KZQ_B,1KZQ_A;%20select%20saved%20selection%20inter_A_B,inter_B_A;%20set%20mode%20all;%20style%20proteins%20c%20alpha%20trace;%20select%20saved%20selection%20inter_A_B,inter_B_A;%20style%20proteins%20schematic;%20show%20selection;%20set%20mode%20all;%20set%20mode%20selection;%20color%20charge;%20set%20mode%20all;%20set%20mode%20selection|||{%22factor%22:1.6021680131846754,%22mouseChange%22:{%22x%22:0,%22y%22:0},%22quaternion%22:{%22_x%22:-0.280627259353463,%22_y%22:-0.14105144602802383,%22_z%22:0.4713906142651267,%22_w%22:0.8241017653566362}}

**Comment by jiywang3** [comment]
I believe this bug has been fixed in the release iCn3D-1.4.0.
