### ISSUE TITLE
What do the colors mean for B factor?

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#100]
Is red good?  Is blue good?  It would really help to have this information in the legend.

<img width="363" alt="Screenshot 2022-11-15 at 1 24 17 PM" src="https://user-images.githubusercontent.com/6663433/202028284-789d8319-eb59-4814-821a-5c21d7557346.png">

**Comment by jiywang3** [comment]
Thanks for your report. We just released iCn3D 3.19.0 to fix it.
