### ISSUE TITLE
The 3D structure information for mutations doesn't always match the info in the 2D representation

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#104]
For this structure, 7LE7:

1.  The 3D view shows 3 contacts to different amino acids in the heavy chain (silver).  But the 2 view only shows one (T108).  The contacts to Y106 and D56 are not shown in the 2D view.

2.  3 hydrogen bonds are shown between R346 and D56 in the 3D view but I can't see any in the 2D view.

https://structure.ncbi.nlm.nih.gov/icn3d/share.html?xCScbRxYX9zqu6Qk6

**Comment by jiywang3** [comment]
Regarding to question #1, the wild type (7L7E) has three contacts, but the mutant (7L7E2) has just one contact. That's correct. You can click the letter "a" to alternate the wild type and the mutant.

Regarding to question #2, in the 2D interaction network view, the contact (grey thin line), hydrogen bonds (green thick line), and salt bridge (cyan thick line) are overlapped with each other between the residues D56 and R346. If you want to see the detailed interactions, you need to click these three buttons in the "Analysis > Interactions" dialog:
![image](https://user-images.githubusercontent.com/11690222/207168723-d5cdaee3-c834-4f65-b4f5-cca63a7ef038.png)
