### ISSUE TITLE
PDB, MMDB, Water, Interactions in iCn3D 

### ISSUE THREAD

**Issue by youkha** [ncbi/icn3d#11]
This is a pending issue but it reveals a number of related issues on data and software.
* We do not have water molecules in iCn3D when using MMDB
If I switch to PDB it is OK as I can have waters BUT, if using PDB directly:
* I lose 2D Interactions window  
* I also do not have Secondary Structure

* "Structural Water: 
Also on 1D waters are in sequence (O.) attached to a chain (as in PDB) that is definitely a PDB issue and may not be that bad actually as it is linked to structure.  It is an issue though to deal with it specifically in interactions (meaning drilling down).

It would be good to discuss some harmonization between PDB and MMDB and/or have MMDB have ALL data from PDB including water and the “alternate” but "official" secondary structure definition.  The secondary structure is a broader issue than water – certainly it should be available when using PDB
 
Whether PDB or MMDB we need both the data and functionality to work identically.
 
Interactions – including water – are needed more and more as it becomes obvious with modern data that crystallographic water is part of the structure NOT ONLY inside a protein but mediating molecular interactions with ligands
As in the example used here 5IH2 
https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?showseq=1&pdbid=5ih2&buidx=1 
(check the paper for the water story).  

In the past we used to discard metal atoms while they are crucial in enzymes for example.  Today we still discard water.  I think a critical eye is needed.
 
Cheers!
Philippe

**Comment by jiywang3** [comment]
I agree that we should include water in MMDB data. I will ask Dachuan to do that.

The 2D interaction data is currently only available for MMDB data. We'll improve this one to ba available to other data as well.

We use DSSP to calculate the secondary structures if they are unavailable. If the PDB structure has only C-alpha atoms, the secondary structures are not calculated using DSSP.

**Comment by jiywang3** [comment]
We just added water molecules to structures that are not bio-assemblies.
