### ISSUE TITLE
MTZ maps don't load properly /don't behave the same as other formats

### ISSUE THREAD

**Issue by ssorgatem** [ncbi/icn3d#112]
Example, using the DSN6 map derived from the same MTZ map:

DSN6 map: 
https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?mmdbid=3dzu&bu=1&command=set%20map%202fofc%20sigma%201.0%20file%20dsn6%20|%20https://edmaps.rcsb.org/maps/3dzu_2fofc.dsn6

MTZ map:
https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?mmdbid=3dzu&bu=1&command=set%20map%202fofc%20sigma%201.0%20file%20dsn6%20|%20https://edmaps.rcsb.org/coefficients/3dzu.mtz

**Comment by jiywang3** [comment]
These two formats were implemented slightly different. The parser of DSN6 map was from RCSB. There is a final translation of the map to match the structure. The parser of MTZ map was from UglyMol, e.g., https://uglymol.github.io/view/?id=3dzu. The map around the structure was generated based on the periodicity. There is no final translation. 

Do you always use MTZ file from RCSB? I noticed the final translation is always zero. We could use the same method as the DSN6 format and improve the current display. But MTZ files from other resources may require a final translation, which is not provided in the MTZ file.

Another difference between DSN6 and MTZ file is the sigma may be different. So your MTZ URL probably needs to use a sigma of 0.2 and change 'dsn6" to "mtz": https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?mmdbid=3dzu&bu=1&command=set+map+2fofc+sigma+0.2+file+mtz+%7C+https://edmaps.rcsb.org/coefficients/3dzu.mtz

**Comment by ssorgatem** [comment]
My ultimate goal is to use structure and maop file from PDB_REDO, and it currently only offers MTZ files for the EDM.

Ah, my bad, I was actually using "mtz" for the type during my testing, I just got it wrong for the example here.

So is that final translation the reason why I can only see like a central box for the EDM instead of the whole structure?

**Comment by jiywang3** [comment]
Yes. Since the translation information was missing, UglyMol shows the unit cell around the structure.

Please wait for a couple of weeks. I will try to another way to load MTZ from RCSB and assume the translation is zero. That might be enough for your project.

**Comment by jiywang3** [comment]
I just made another release to accept MTZ from RCSB specifically. You can simply change "file mtz" to "file rcsbmtz" in the URL. One example is https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?mmdbid=3dzu&bu=1&command=set+map+2fofc+sigma+0.2+file+rcsbmtz+%7C+https://edmaps.rcsb.org/coefficients/3dzu.mtz. It didn't cover the whole structure. But it's much better than the version with "file mtz".

The UI is in the menu "File > Open File > Electron Density > .. > Load RCSB MTZ".

**Comment by ssorgatem** [comment]
It seems to work well even with PDB_REDO mtz files, like:
https://pdb-redo.eu/db/3dzu/3dzu_final.mtz

However, I was unable to load the structure from PDB_REDO (I could in earlier versions), it gets stuck at "loading"
https://pdb-redo.eu/db/3dzu/3dzu_final.cif

**Comment by jiywang3** [comment]
The bug was fixed: https://www.ncbi.nlm.nih.gov/Structure/icn3d/?type=mmcif&url=https://pdb-redo.eu/db/3dzu/3dzu_final.cif
