### ISSUE TITLE
"load url" command broken in icn3d_3.29.5

### ISSUE THREAD

**Issue by ssorgatem** [ncbi/icn3d#113]
The command `load url https://pdb-redo.eu/db/3dzu/3dzu_final.cif | type mmcif` works fine on icn3d_3.29.4 but fails on icn3d_3.29.5, as it's trying to append the url to the site url as if it were a local file.

https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?command=%22load%20url%20https://pdb-redo.eu/db/3dzu/3dzu_final.cif%20|%20type%20mmcif%22

`Failed to load resource: the server responded with a status of 404 ( https://www.ncbi.nlm.nih.gov/Structure/icn3d/,https://pdb-redo.eu/db/3dzu/3dzu_final.cif )`

**Comment by jiywang3** [comment]
Thanks for the bug report. It was fixed: https://www.ncbi.nlm.nih.gov/Structure/icn3d/?type=mmcif&url=https://pdb-redo.eu/db/3dzu/3dzu_final.cif.
