### ISSUE TITLE
Bug 2D interations - asymetric unit

### ISSUE THREAD

**Issue by youkha** [ncbi/icn3d#12]
https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?showseq=1&mmdbid=6042&buidx=0
In this example (as in others)
using the asymmetric unit - a dimer - we do not get the cain chain interactions (let alone the domain domain hpefully in the future) we get a single chain in the 2D interaction window rather than 2 chains interacting.

**Comment by jiywang3** [comment]
Yes, it's a bug. I will ask Dachuan to fix it.

**Comment by jiywang3** [comment]
This is fixed in the new version iCn3D 2.0.0.
