### ISSUE TITLE
2D interactions

### ISSUE THREAD

**Issue by youkha** [ncbi/icn3d#13]
The notion of symmetry should be enforced in a general way but this is a deep issue as it shoudl be a core functionality in 3D as well as 2D.
However there are bugs - for example in some cases if there is an interaction A-L there the symmetrical A'-L' should be there 
example: 2 ligand in symmetrically equivalent positions show different links (interactions) in the 2D cartoon:
https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?showseq=1&mmdbid=116264&buidx=1

**Comment by jiywang3** [comment]
The 2D interaction cartoon seemed symmetric to me.
