### ISSUE TITLE
Bug on display selection with labels applied to another selection

### ISSUE THREAD

**Issue by youkha** [ncbi/icn3d#14]
This concerns label per residue, have not checked all options
 (may be as designed - yet change design)

using label as opposed to Schematic
all labels of a selection appear even if another selection is displayed  This does not happen with schematics
yet schematics cannot mix with other representations currently

See also the issue of colring of labels on a residue basis (unlike schematics that adopt the residue color)

**Comment by jiywang3** [comment]
This is by design and could be improved. If you change the displayed residues, you can remove the previous label by selecting "Analysis" -> Label -> Remove.
