### ISSUE TITLE
issue with state files

### ISSUE THREAD

**Issue by mxasf** [ncbi/icn3d#19]
Hi all -
First I want to thank everyone for this great tool.   I teach college organic chemistry and use this to show protein-drug interactions.   I love PyMol but for teaching, this is much more very ideal for teaching purposes and something students can use at home.

I noticed an issue with "state files" not saving all the key details of the state, sort of like how a  PyMol project file works.    Here are three attachments
(a) a PNG that was created showing biotin-streptavidin and its key interactions
(b) the statefile that was saved after step (a)
(c) after I re-loaded the statefile, I create a new PNG.  I would imagine it should be the same as (a) but it is different in color, and the key residues are not shown.

It appears that not all aspects of the "state" are being saved. 
Thanks!!!!  -marc anderson (SFSU Department of Chemistry)

![1STP-initial](https://user-images.githubusercontent.com/59582803/71850365-f4dc8680-3088-11ea-82fb-5af8712cbcf3.png)

[1STP_statefile.txt](https://github.com/ncbi/icn3d/files/4027890/1STP_statefile.txt)

![1STP-later](https://user-images.githubusercontent.com/59582803/71850377-01f97580-3089-11ea-971d-ca4c95a7fbf1.png)

**Comment by jiywang3** [comment]
Hi Marc,
Thanks for your detailed bug report. I just fixed it. Please let me know if you have any suggestions. By the way, it's easier to use "Share Link" in the File menu than to save statefile.
Jiyao
