### ISSUE TITLE
NFE - Interactions improvements

### ISSUE THREAD

**Issue by youkha** [ncbi/icn3d#21]
Interactions
 
Highlights - need to be able to select a set of interactions [with Command-click-highlight not just one at a time.  Then we eventually want to name that set
[we need to have something general]
 
Simplified highlights - CA to CA or centered to centroid summing up the atom level contacts between 2 residues using section proportional to sum ... or something along these lines. We could estimate energies on non bonds and hbonds ... and have section proportional, although we are not minimizing structures ... that may be an issue
 
We need carbohydrate links as in Cn3D example N4/N168 and we may need to handle them together, not separately.  Not sure how it is best to achieve this
Glycosylation is important ... so connecting carbohydrates to the right N (or O- eventually) is important - it must be in the PDB as CONNECT statement
 
We need highlights of H-bonds and non bonds.  There are 2 types sets to envision
- sets of residues
- sets of [interacting] pairs
And a relationship between the two
 
Also on the stats about interactions - precisely - the number of residues and residue pairs is useful in addition to the total number reported

**Comment by jiywang3** [comment]
Implemented.
