### ISSUE TITLE
Distance calculation

### ISSUE THREAD

**Issue by MendesMarcus** [ncbi/icn3d#26]
The distance calculation function maybe it is not working correctly. After I made a selection of two residues in a different chain, I clicked on "Analysis," "Distance," and "between two sets." It opened a box, and I choose "selected" in both the first and second set. The result is always 0 angstrom of distance.

**Comment by jiywang3** [comment]
You need to define two sets first and select each set when you click "Analysis > Distance > between two sets". There are several ways to define sets. You can use the input "Search Seq." at the top right corner. This will automatically save a set for each search. If you select residues in 3D, you can click "Select > Save Selection" to save the set. If you click "Analysis > Sequences & Annotations > Details", you can drag on the sequences and save with a name near the line "Selection: Name" at the top.
