### ISSUE TITLE
Quickly dragging the molecule viewer will highlight the tooltip for residue text and stop drag

### ISSUE THREAD

**Issue by bha008** [ncbi/icn3d#28]
Could make 3d navigation less smooth. It might be because the tooltip is spawned in the path of the mouse drag

**Comment by jiywang3** [comment]
From my experience, the tooltip on residues does not affect dragging the molecule. Could you be more specific about how the dragging was stopped by the tooltip?

**Comment by bha008** [comment]
If you drag very fast, the tooltip text gets highlighted and the mouse up event doesn't get triggered. This causes the drag to keep happening even without holding down left click

**Comment by jiywang3** [comment]
By the way, you can use cfg['mmtfid'] = '7ddd' instead of cfg['pdbid'] = '7ddd'. That will speed up the data loading.
