### ISSUE TITLE
Right click navigation always brings up context menu

### ISSUE THREAD

**Issue by bha008** [ncbi/icn3d#29]
This is happening on Chrome. The context menu always shows up after letting go of right click and drag.

**Comment by jiywang3** [comment]
Although  we encourage users to download images using the menu "File > Save File > iCn3D PNG Image", some users may still download image by clicking the right mouse button. Does the default context menu bother you? Do you think it will be cleaner if iCn3D blocks the default context menu?

**Comment by bha008** [comment]
If there is a drag event with the right click, I don't expect a context menu to show up. I can see it being useful if the menu only showed up with a right click without (major shift) in mouse position

**Comment by jiywang3** [comment]
I blocked the context menu in iCn3D. We encourage users to save image at the menu "File > Save Files > iCn3D PNG Image".
