### ISSUE TITLE
Align Sequence to Structure is not working

### ISSUE THREAD

**Issue by digitaltodd** [ncbi/icn3d#31]
I tried several things:

1. Started with a FASTA sequence and single chain structure, when load is clicked I get a blank (black) viewer window. 
2. Next tried the default query (NP_001108451.1 to 1TSR_A) as a test. Same result as above - blank viewer window. 
3. Tried variants on 1. remove spaces - remove fasta header, add _A to 1AZI - no luck. 
The other alignment options - structure to structure, multiple chains - do work. 

![Screen Shot 2021-04-24 at 1 13 45 PM](https://user-images.githubusercontent.com/6664990/115972358-b2032400-a502-11eb-868b-d762de4c4fee.png)

**Comment by jiywang3** [comment]
I just fixed the bug. You can try it again.

**Comment by digitaltodd** [comment]
It works, thanks!

I noticed a couple of things that make it a little harder than is should be - IMO

1. The PBD ID in Structure ID must be in CAPS - I’m using 1AZI_A for the example. If I enter 1azi_a - the new view simply loads the 1AZI structure. If on the other hand I enter 1AZI_A, I get an alignment

2. The “fasta” sequence - must be a plan sequence, no header. Technically that is not fasta. If the header is in place I get a “cannot load MMDBID error."

3. You have to be sure to remove the example Sequence ID. Sequence ID takes precedence over the pasted sequence. This can be easily missed.  

My test sequence = 
>pdb|1AZI|A Chain A, MYOGLOBIN
GLSDGEWQQVLNVWGKVEADIAGHGQEVLIRLFTGHPETLEKFDKFKHLKTEAEMKASEDLKKHGTVVLT
ALGGILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISDAIIHVLHSKHPGDFGADAQGAMTKALELFRN
DIAAKYKELGFQG

**Comment by jiywang3** [comment]
1. PDB chain name is case-sensitive. So "A" and "a" are different. The PDB ID could be upper-case or lower-case. 
2. I fixed the issue with FASTA sequence. Now iCn3D accepts the sequence with or without the title line.
3. Now iCn3D reminds users to remove one of Sequence ID and FASTA Sequence if both are available.
Thanks for your report.
