### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by MendesMarcus** [ncbi/icn3d#32]
I want to ask about the licensed software, e.g., Delphi. How did you get these licenses? If I intend to use iCn3D in my server, do I need to require permission to use them?

**Comment by jiywang3** [comment]
You can contact Columbia University to get the license. The contact information is listed at https://honiglab.c2b2.columbia.edu/software/cgi-bin/software.pl?input=DelPhi. If you don't want to use the licensed part, I can add an option to hide it.

**Comment by MendesMarcus** [comment]
Hi Jiyao

Thank you for the swift reply. I checked the license, and it seems ok to use it, but I will forward it to the lawyer department of LJI to check it properly. Also, I would ask you if it is possible to make an iCn3D version free of license (as you said, an option to hide the licensed part). I think it is better for the tool since this an incredible viewer, and probably other users will want to host it on their website.

**Comment by digitaltodd** [comment]
I second that. Thanks

**Comment by jiywang3** [comment]
Thanks for your suggestions! Now you can add a URL parameter "hidelicense=1" to hide the features requiring license. One example is at https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?mmdbid=1tup&hidelicense=1.
