### ISSUE TITLE
Custom tooltip information

### ISSUE THREAD

**Issue by bha008** [ncbi/icn3d#33]
Is it possible to append data to the tooltips when hovering over a residue?
![image](https://user-images.githubusercontent.com/1900546/122447982-297c8f00-cf59-11eb-8b06-e49d7fb73ba1.png)
 For example, if I add custom coloring (similar to the b factor coloring), is there a built in function to display the values assigned to each residue in the tooltip?

**Comment by jiywang3** [comment]
That's a good question. You need to update your code to the version 3.2.1 first. You can then follow the source code in the file "https://github.com/ncbi/icn3d/blob/master/example.html" to modify a function in the class "Picking". Basically you can modify the function as follows: icn3d.Picking.prototype.showPicking = function(...

**Comment by jiywang3** [comment]
I added the instruction in the help menu: https://www.ncbi.nlm.nih.gov/Structure/icn3d/icn3d.html#modifyfunction
