### ISSUE TITLE
applyCommandCls.applyCommand() does not redraw

### ISSUE THREAD

**Issue by bha008** [ncbi/icn3d#34]
applyCommandCls.applyCommand() does not redraw the 3d view until the window is resized.

Example)
![image](https://user-images.githubusercontent.com/1900546/122469580-f8f51f00-cf71-11eb-98e3-c9b2ce1aef3c.png)

![image](https://user-images.githubusercontent.com/1900546/122469659-10cca300-cf72-11eb-89b0-28d3697ef31c.png)
Commands are run using applyCommand(), but nothing visually changes. The console shows the commands

After changing the window size, the colors are updated:
![image](https://user-images.githubusercontent.com/1900546/122469924-57220200-cf72-11eb-8d32-467e29df9fff.png)

**Comment by jiywang3** [comment]
That's expected. applyCommand() is typically used to execute all the commands. The draw() function is only required to execute once after all commands are processed. So you need to specifically execute the draw function (e.g.,  ic.drawCls.draw()) if you want to update the view.

**Comment by bha008** [comment]
Great, thanks!
