### ISSUE TITLE
load pdb from URL - icn3d-3.2.1

### ISSUE THREAD

**Issue by namratasp20** [ncbi/icn3d#35]
Hi team, 

I am interested in visualising PDB files by loading them from URL and have downloaded icn3d-3.2.1 for the same

When I open example.html (Embed Multiple iCn3D Viewers in One Page) in browser, all pdb structures are visible except the one being fetched by url.

div0 to div3 and div5 display respective pdb structures , however div4 (which uses url to fetch PDB) displays a empty black box.

Could you help me understand why loading PDB from url is not working ?
Are there any settings or configurations to be taken care of to have loading PDB from url functional ?

**Comment by jiywang3** [comment]
When you load PDB file from a URL, either the host name of the URL should be the same as the host name of your web site, or your web host should be configured to allow access from other domains.

**Comment by namratasp20** [comment]
Thanks for the response. I am able to visualize structures through url now
