### ISSUE TITLE
View RNA pdb files

### ISSUE THREAD

**Issue by namratasp20** [ncbi/icn3d#36]
I have few pdb files generated for RNA using rnacomposer (http://rnacomposer.cs.put.poznan.pl/)

When I try to load these files in the viewer, 3D structure is not available

Thus, wanted to understand icn3d can visualize PDB files of proteins only ?

Following is the first of few lines of pdb file obtained through above site for input RNA sequence
MODEL        1
ATOM      1 HO5'   G A   1      -0.154  -0.520   0.011  1.00  0.00           H  
ATOM      2  O5'   G A   1       0.395  -0.651  -0.766  1.00  0.00           O  
ATOM      3  C5'   G A   1       1.734  -0.303  -0.401  1.00  0.00           C  
ATOM      4  H5'   G A   1       1.995   0.660  -0.843  1.00  0.00           H  
ATOM      5 H5''   G A   1       2.423  -1.059  -0.773  1.00  0.00           H  
ATOM      6  C4'   G A   1       1.874  -0.213   1.100  1.00  0.00           C  
ATOM      7  H4'   G A   1       2.937  -0.120   1.327  1.00  0.00           H  
ATOM      8  O4'   G A   1       1.077   0.908   1.575  1.00  0.00           O  
ATOM      9  C1'   G A   1       0.348   0.524   2.727  1.00  0.00           C  
ATOM     10  H1'   G A   1       0.480   1.314   3.467  1.00  0.00           H  
ATOM     11  N9    G A   1      -1.067   0.463   2.376  1.00  0.00           N  
ATOM     12  C4    G A   1      -2.077  -0.059   3.147  1.00  0.00           C  
ATOM     13  N3    G A   1      -1.937  -0.607   4.371  1.00  0.00           N  
ATOM     14  C2    G A   1      -3.090  -1.019   4.862  1.00  0.00           C  
ATOM     15  N2    G A   1      -3.129  -1.581   6.073  1.00  0.00           N  
ATOM     16  H21   G A   1      -2.267  -1.680   6.592  1.00  0.00           H  
ATOM     17  H22   G A   1      -4.003  -1.883   6.471  1.00  0.00           H  
ATOM     18  N1    G A   1      -4.289  -0.910   4.205  1.00  0.00           N  
ATOM     19  H1    G A   1      -5.118  -1.258   4.659  1.00  0.00           H  
ATOM     20  C6    G A   1      -4.459  -0.350   2.944  1.00  0.00           C  
ATOM     21  O6    G A   1      -5.587  -0.299   2.442  1.00  0.00           O  
ATOM     22  C5    G A   1      -3.227   0.103   2.403  1.00  0.00           C  
ATOM     23  N7    G A   1      -2.946   0.716   1.189  1.00  0.00           N  
ATOM     24  C8    G A   1      -1.657   0.910   1.218  1.00  0.00           C  
ATOM     25  H8    G A   1      -1.107   1.376   0.414  1.00  0.00           H  
ATOM     26  C2'   G A   1       0.924  -0.809   3.199  1.00  0.00           C  
ATOM     27  H2'   G A   1       0.164  -1.430   3.679  1.00  0.00           H  
ATOM     28  O2'   G A   1       2.033  -0.551   4.040  1.00  0.00           O  
ATOM     29 HO2'   G A   1       2.677  -1.238   3.870  1.00  0.00           H  
ATOM     30  C3'   G A   1       1.362  -1.422   1.875  1.00  0.00           C

**Comment by jiywang3** [comment]
I just released iCn3D 3.2.2. It should be working. After loading your PDB file of nucleotides, you may need to change the style from "Style > Nucleotides > cartoon" to "Style > Nucleotides > Stick" if the nucleotide has no cartoon display.

**Comment by namratasp20** [comment]
Thank you for the update. I am able to view to PDB file of nucleotides in cartoon as well as stick styles
