### ISSUE TITLE
Blue cube around sugars on glycosylated proteins

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#37]
Hi, 

It seems that the Glycans > Add Cartoon command is on by default.  Can we have this off by default instead?

thanks!

**Comment by jiywang3** [comment]
Yes, I think we can do that in the next release.

**Comment by youkha** [comment]
Jiyao not sure it is best ::: maybe we should think of more preferences

**Comment by jiywang3** [comment]
Philippe, that's a good idea. I will add it to "Style > Preference". By default, the transparent glycan cube/sphere shapes still show up. But once a user turns it off in the preference, it will be remembered in cache and persistent for the user.

**Comment by digitalbio** [comment]
Hi Jiyao,

I think controlling this through Preferences is fine.  But can it be Off by default and not On?

My students aren’t always able to work at a single computer.  

thanks,

Sandy

**Comment by jiywang3** [comment]
Hi Sandy,
Sure. I will make if off by default. It's a good point that students use different computer and thus lose the settings in the Preferences.
Jiyao

**Comment by digitalbio** [comment]
thanks!

Sandy

**Comment by jiywang3** [comment]
Hi Sandy,

The default was changed to hide the glycans. Users can change the default in "Style > Preferences". You can check it out.

Jiyao
