### ISSUE TITLE
Color legend for alphafold confidence

### ISSUE THREAD

**Issue by siupenyau** [ncbi/icn3d#42]
Hello,

Thank you very much for releasing iCn3D. I am checking the 3D protein structure predicted with alphafold2. I am evaluating the alphafold confidence color of the structure. Would you please let me know where I can find the color legend for the confidence?

With best wishes,

Timothy Ng

**Comment by jiywang3** [comment]
Thank you for your bug report! I fixed the bug so that the legend will be shown for any structures when the menu "Color > AlphaFold Confidence" is clicked. Please let me know if you see any problems.
