### ISSUE TITLE
Defined set color doesn't update when changing colors

### ISSUE THREAD

**Issue by bha008** [ncbi/icn3d#44]
For example: 
![image](https://user-images.githubusercontent.com/1900546/134035399-8ad44b63-e7f6-4193-bafe-87934a532505.png)
chain 7DDD_C is colored in white

I load the selection through defined set and perform Color > Unicolor > ... > Cyan. The 3d model does not update the first time and will only recolor the second time I pick cyan. 

After that, I expect the text to change to cyan as well, but it remains the old color

![image](https://user-images.githubusercontent.com/1900546/134035945-69cca5fa-deb3-48ec-ab43-b30695c57a2a.png)

7DDD_C is above AY.1 in white

**Comment by jiywang3** [comment]
The bug has been fixed. You can try it again.

**Comment by bha008** [comment]
It's working, thanks!
