### ISSUE TITLE
Domains Information in iCn3D

### ISSUE THREAD

**Issue by youkha** [ncbi/icn3d#5]
Both Structural and CDD domain info should be available as an attribute of a domain but also within chains with multiple domains 
Onegood use of that would be of course coloring, labeling ....

A place where it would be very useful would be in a table for a large system (as avalaible today as a selection table - with only chains names and # res in chain) we should/could have CDDs as a column and also structural domains [we may need to work on naming VAST domains to make it great, we may also enable nomenclaures to be added such as SCOP, maybe through a user interface - domain definitions as possibly sets that we can read in as well as save)

The info is pretty much available in MMDB pages ...

**Comment by jiywang3** [comment]
Good idea. We'll show the domain information in the future.
