### ISSUE TITLE
Unable to select single nucleotide

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#51]
I would like to select a single nucleotide in 7OZV from the sequence view.

1. Opened Sequences & Annotations.
2. Opened the Details tab.
3. Chose the two nucleotide chains 
4. Chose View Selection in order to hide the protein.
5. Clicked Toggle Highlights to remove the highlights.
6. Used cursor to click the second X (X9) but when I click the chain, the whole sequence is highlighted.  I can deselect a few bases by clicking and dragging but I'm not able to select a single base.  

Expected behavior - I thought I should be able to click the cursor inside the sequence and select a single base.  I also expected that I should be able to select additional bases by clicking and dragging.

**Comment by jiywang3** [comment]
This bug was introduced today and fixed! Thanks!
