### ISSUE TITLE
Highlights disappear when I choose View selection - but molecule is still selected

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#54]
I did the following:

1.  Selected a single chain of 7ODF.  Result:  the chain is selected and has a yellow highlight.
2. Changed the drawing style to Ball and Stick.  Result:  Each atom has a yellow highlight.
3. Change the coloring style to Atom.  Result:  Each atom has a yellow highlight.
4. Chose View Selected.  

**Result**:  Other molecules are hidden.  The yellow highlight disappears from the structure window, but the sequence is still highlighted. 

Problem: I think both the structure and the sequence should stay highlighted until I either toggle highlights or clear the selection.

> load mmdb 7ODF | parameters &mmdbid=7ODF
> set pk atom
> view annotations
> set annotation cdd
> select chain 7ODF_A
> style proteins ball and stick
> color atom
> show selection

**Comment by jiywang3** [comment]
Users usually find the highlight annoying when it is used for all displayed atoms in 3D. That's why we removed the highlight on purpose. But the residues are a subset in the sequence window and require the highlight. We'll leave it for now unless we have a better solution.
