### ISSUE TITLE
The Disulfide bond annotations are in the Sequences and Annotations section are incorrect. Some cysteines are not shown and residues without sulfur are annotated as containing disulfide bonds.

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#57]
6M0J has two protein chains and both of them have disulfide bonds.  But when I go to the Details tab and click the Disfulfide bonds check box the cysteines only appear in protein chain A.

The first image shows how the cysteines are missing from the Disulfide bonds track for chain E.
<img width="515" alt="chain E" src="https://user-images.githubusercontent.com/6663433/139514623-cb0fc823-d62b-4ce7-a1fd-5fa2db13be8d.png">

The second image shows how the cysteines are present in the Disulfide bonds track for chain A.
<img width="741" alt="chain A" src="https://user-images.githubusercontent.com/6663433/139514625-453a5fcd-1516-4f5a-bb4d-54099913fe6b.png">

**Comment by digitalbio** [comment]
Sometimes the Disulfide bond track shows residues that don't form disulfide bonds.  For example, with structure 7BZ5, chain H has a Leucine appearing in the Disulfide bond track and an Isoleucine in the Disulfide bond track in chain L
<img width="627" alt="disulfide bond annoations" src="https://user-images.githubusercontent.com/6663433/139561386-0327f120-2ba7-41dd-801c-7c33eb8d441a.png">
.

**Comment by jiywang3** [comment]
Thanks for the bug report. It has been fixed!

**Comment by digitalbio** [comment]
Confirmed!  Thanks!
