### ISSUE TITLE
Unable limit labels to selected residues

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#59]
I had two amino acids that I wanted to label.  Only two are visible.

I opened the Analysis window and chose "Label > per residue and number"
<img width="326" alt="Screen Shot 2021-10-30 at 5 22 24 PM" src="https://user-images.githubusercontent.com/6663433/139561836-5c751860-a592-4ee6-89ef-45d4c99beee2.png">
 

Lots of labels appeared where I only want to see two labels (C344 and C361).
<img width="1301" alt="crazy labels" src="https://user-images.githubusercontent.com/6663433/139561853-930c08d7-e9d9-41ed-b5d4-688a1fc44979.png">

**Comment by jiywang3** [comment]
I can't reproduce it. Could you specify your steps?

**Comment by digitalbio** [comment]
This worked fine today.  I will close until I see it happen again and them make sure I can reproduce it.
