### ISSUE TITLE
Clicking "Toggle Highlight" causes my selected amino acids to jump out of the view

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#60]
1.  I selected the cysteines on each side of a disulfide bond.  
2.  I chose View Selected to hide everything else.
3.  I selected Toggle Highlight to remove the highlight.
4.  The amino acids disappeared.  

**Problem**:
I had to zoom way out in order to find the two amino acids again.
I don't think changing the highlight should cause the selected amino acids to change their size or position.

**Comment by jiywang3** [comment]
I can't reproduce it. If the structure is moved away, you could try the menu "View > Reset > Orientation" to bring it back. 

You could also use the expanded "Toggle Highlight" button after you click the "Toolbar" near the help menu.

**Comment by digitalbio** [comment]
Ok, thanks!  I didn't realize those buttons were there.

**Comment by digitalbio** [comment]
I'll close this until I see it again.
