### ISSUE TITLE
Select by Distance is not working with metals

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#62]
Structure 1UVQ

1.  I clicked on the Zinc in the 3d structure to select it. The yellow halo appeared around it.
2.  Opened Select > by Distance
3.  I used "selected" for the first set, a radius of 4 A, and "non-selected" for the second set, clicked Display
Result:  The yellow halo disappeared and nothing happened.

What I expected:  I expected to see one or two amino acids selected.  If I opened Sequences & Annotations, clicked Details, then Interactions, I could see D76 and H81 interact with the Zinc.

Here are the commands that appeared below the structure window:

> load mmdb 1UVQ | parameters &mmdbid=1UVQ
> pickatom 3108(chain: 1UVQ_ZN, residue: ZN, number: 1003, atom: ZN)
> select zone cutoff 4 | sets selected non-selected | false

**Comment by digitalbio** [comment]
Also - this process worked with 3R0L.  I have a video of the process here [https://youtu.be/XGYWUMAmZX0]

**Comment by jiywang3** [comment]
This was fixed. Thanks for the report.

**Comment by digitalbio** [comment]
Confirmed.  :-)
