### ISSUE TITLE
Confusion with structure alignments

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#63]
For some structures, I can go to the NCBI structure database, click a chain, select a structure in the VAST results, choose iCn3, and see a structure alignment in iCn3D.  The image below shows a case where I did this by using 6M0J and then I chose 7L3NB as the structure.

<img width="1378" alt="Screen Shot 2021-11-21 at 1 04 25 PM" src="https://user-images.githubusercontent.com/6663433/142778888-63f66507-3f5e-4e72-96d8-ef6c212407f3.png">

If I open iCn3D, and choose Align > Structure to Structure, enter the same PDB IDs, and choose All Matching Molecules Superimposed, I get a message saying that these two structures do not have 3D alignment data.

<img width="376" alt="Screen Shot 2021-11-21 at 1 07 27 PM" src="https://user-images.githubusercontent.com/6663433/142778968-aef37b97-8652-41d2-9874-ac97e2184ad2.png">

I don't understand why I'm getting a different result with iCn3D than I get from the NCBI structure database.

**Comment by digitalbio** [comment]
Also - when I load aligned structures by using the View 3D Alignment option from VAST, iCn3D is really slow.  I'm not sure if this is related.

**Comment by jiywang3** [comment]
NCBI structure database has two kinds of alignment: VAST and VAST+. The VAST alignment is typically between two chains as you saw between 6M0J_E and 7L3N_B. The VAST+ alignment is typically between two biological assemblies such as 6M0J and 7L3N. In iCn3D, the option "File > Align > Structure to Structure" uses the VAST+ alignment. The option "File > Align > Multiple Chains" using just chains as inputs uses the VAST alignment.  Hope this clarifies the difference a bit.

**Comment by digitalbio** [comment]
Ok, I'll try that and see if it works.  

I was confused because of the error message saying that there wasn't alignment data.  

The error message seemed to contradict the results that I saw from VAST.

**Comment by digitalbio** [comment]
Oh, I never use VAST+ because it doesn't work as well for things I do.

Do you know, with VAST+, if there's as way I can search with more than one PDB ID?  I only seem to be able to make this work with one ID>

<img width="688" alt="Screen Shot 2021-11-21 at 2 21 21 PM" src="https://user-images.githubusercontent.com/6663433/142782023-6a240611-f274-46e8-8f73-bf1f18a60735.png">

**Comment by digitalbio** [comment]
I also haven't used VAST+ because when search for alignments, I can find them in the old VAST and I can't find them in VAST+.  So, it hasn't seemed very useful.

**Comment by jiywang3** [comment]
This help page talks about VAST and VAST+. I updated the error message to 'These two MMDB IDs [PDB ID 1] and [PDB ID 2] do not have 3D alignment data in the VAST+ database. You can try the VAST alignment by visiting the VAST+ page https://www.ncbi.nlm.nih.gov/Structure/vastplus/vastplus.cgi?uid=[PDB ID] (e.g., uid=1KQ2), and clicking "Original VAST"'. The VAST+ page can be used for both VAST+ and VAST search.
