### ISSUE TITLE
Can't hide sidechains

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#65]
Structure:  2KBH

I want to show the backbone in Ball and Stick and hide the side chains.

Here's what I did:

1.  Selected Style > Proteins > Ball & Stick. 
2. Selected Color > Atom

Now, I want to hide the sidechains so, 

I opened Style > Sidechains > Hide

Result:  nothing happened.

So, I selected the protein chain, opened Style > Sidechains > Hide

Result:  nothing happened.

Here are the commands:

> load mmdb 2kbh | parameters &mmdbid=2kbh
> style proteins ball and stick
> color atom
> style sidec nothing
> style sidec nothing
> style sidec nothing
> view annotations
> set annotation cdd
> select chain 2KBH_A
> style sidec nothing
> show annotations all chains
> show annotations all chains
> set view detailed view
> style sidec nothing
> select chain 2KBH_A
> style sidec nothing
> style sidec ball and stick
>

**Comment by jiywang3** [comment]
The selection (main chain vs side chain) is in the "Select" menu. The "Style" menu didn't change the selection. So you can try the "Select" menu, then the "Style" menu.

**Comment by jiywang3** [comment]
You could apply "View Selection" at the end to hide the partial bonds to side chains.

**Comment by digitalbio** [comment]
That sounds complicated.  

Now, I'm curious.  What is the "Style > Side chains > Hide" command supposed to do?  

<img width="328" alt="Screen Shot 2021-11-22 at 2 22 35 PM" src="https://user-images.githubusercontent.com/6663433/142944153-a7a2f305-30f7-4be8-b476-fc99fdd1523a.png">

**Comment by jiywang3** [comment]
iCn3D chose to add side chain as another layer on top of protein. When a user shows the protein as ribbon style and shows the side chain as ball-and-stick, he can choose to hide the side chain.

**Comment by digitalbio** [comment]
It think it would make sense to have the Hide side chain command be more universal and hide side chains in all use cases.
