### ISSUE TITLE
Selecting and coloring one chains changes the color in all unselected chains too 

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#66]
1.  Went to 7A94 at the NCBI.
2. Chose VAST+
3. Clicked 7KRQ
4. Opened in iCn3D web app.
5. Click the chain name for 7A94_A in the "Select residues in aligned sequences" window  (this window appears when the app opens).
6. Color > Cyan > Turquoise

Expected result:  only chain A would change color to turquoise

Result:  It took about 30 seconds for the color to be applied, then all the chains in alignments changed color to turquoise - I think the only chain that should have changed was the chain that I selected. 

<img width="670" alt="Screen Shot 2021-11-22 at 11 57 06 AM" src="https://user-images.githubusercontent.com/6663433/142927013-bf0f678a-21b5-4a3c-975e-7b47e0453e4a.png">

**Comment by jiywang3** [comment]
This has been fixed! Thanks!

**Comment by digitalbio** [comment]
Confirmed, thanks!
