### ISSUE TITLE
The Alternate key doesn't always work

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#68]
Browser: Firefox

1.  I annotated two aligned structures so that each pair of aligned chains had the same color.  
2.  I deleted all the defined sets except for the two structures (7A94 and 7KRQ).  
3.  I clicked one structure in Defined sets and clicked View Selected in order to see it.
4.  I clicked the A key to alternate between structures but nothing happened.
5.  I had to clear the selection three times to get the alternate key to work.

> load alignment 192475,1,200478,1 | parameters &showalignseq=1&align=192475,1,200478,1&atype=0
> view interactions
> select chain 7A94_D
> color F4A460
> select chain 7A94_A
> select alignChain 7KRQ_C
> select alignChain 7KRQ_C
> select alignChain 7A94_A
> select sets align_7KRQ_C or align_7A94_A
> select alignChain 7A94_A
> color 0FF
> select alignChain 7KRQ_C
> color 0FF
> select alignChain 7A94_B
> select alignChain 7KRQ_A
> select sets align_7A94_B or align_7KRQ_A
> color F0F
> select alignChain 7A94_C
> select alignChain 7KRQ_B
> select sets align_7A94_C or align_7KRQ_B
> color A52A2A
> defined sets
> defined sets
> select sets 7A94_A
> select sets 7A94_A or 7A94_B or 7A94_C or 7A94_D or 7A94_Misc or 7A94_cons or 7A94_nalign or 7A94_ncons
> select sets 7A94_A or 7A94_B
> select sets 7A94_A or 7A94_B or 7A94_ncons
> select sets 7A94_A or 7A94_B or 7A94_nalign or 7A94_ncons
> select sets 7A94_A or 7A94_B or 7A94_cons or 7A94_nalign or 7A94_ncons
> select sets 7A94_A or 7A94_B or 7A94_C or 7A94_cons or 7A94_nalign or 7A94_ncons
> delete selected sets
> select sets 7A94_D
> select sets 7A94_D or 7A94_Misc
> delete selected sets
> select sets 7KRQ_A
> select sets 7KRQ_A or 7KRQ_B or 7KRQ_C or 7KRQ_Misc or 7KRQ_cons or 7KRQ_nalign or 7KRQ_ncons or align_7A94_A or align_7A94_B or align_7A94_C or align_7KRQ_A or align_7KRQ_B or align_7KRQ_C or chemicals or ions or protein_aligned or proteins
> delete selected sets
> select sets 7A94
> show selection
> alternate structures
> select sets 7KRQ
> clear all
> clear all
> clear all

**Comment by jiywang3** [comment]
The alternation only works for your selection. If your selection has just one structure, it doesn't alternate. In your case, you need to click the "All Atoms/Selection" toggle near the "Help" menu to select all structures, then do the alternation.

**Comment by digitalbio** [comment]
Thanks!
