### ISSUE TITLE
The amino acid names in on the X axis of the 2D interaction map are too difficult to read

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#69]
Web browser - Firefox.  [*I have to use Firefox because many features don't work in Safari or Chrome.]

1.  Loaded 7BZ5.
2. Opened Select > by Distance, chose chains H & L.
3. Named selection "epitope"
4. Opened Analysis > Interactions 
5. Deselected Halogen bonds, pi cation, and contacts/interactions
6. Selected epitope and H and L chains for first and second sets.
7. Clicked 2D Interaction map.

Result - the map is nice but I can't read the information on the X axis.  The text needs to be spaced differently.  

Attempted work arounds:  

1.  I tried changing the scale but this didn't change the text spacing.
2.  I tried downloading the PNG file but it didn't contain an image. I uploaded the file below.

<img width="636" alt="Screen Shot 2021-11-24 at 6 33 56 AM" src="https://user-images.githubusercontent.com/6663433/143258501-7e3f7b1b-c8ec-4269-96b4-039e3a91ccff.png">

![7BZ5_scatterplot](https://user-images.githubusercontent.com/6663433/143258466-d80e153d-ba07-4b5b-9cff-ca32b0de3b92.png)

**Comment by jiywang3** [comment]
Are you working in Mac? The font seemed OK to me both in Mac and PC. Maybe your screen resolution is low?

What's the problem in Safari and Chrome? I typically work in Chrome.

**Comment by jiywang3** [comment]
OK. I reproduced the same problem in Mac Firefox. I will modify it.

**Comment by jiywang3** [comment]
The bug was fixed. You need to clear cache and try it again.

**Comment by digitalbio** [comment]
Thank you!  It looks very nice!
