### ISSUE TITLE
Unable to reset information in the 2D Diagram viewer

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#73]
Structure:  2DN2

1.  I select a heme and a protein chain.  (chain D and the attached heme)
2.  View Selection.
3.  Click Reset All

Result:  All four chains reappear in my structure

Bug:  The 2D Diagram viewer still only shows two chains. 

Here are the commands:

> load mmdb 2dn2 | parameters &mmdbid=2dn2
> view interactions
> select chain 2DN2_D
> select chain 2DN2_HEM4
> show selection
> reset

Here's what it looks like:

<img width="997" alt="Screen Shot 2021-11-24 at 5 22 12 PM" src="https://user-images.githubusercontent.com/6663433/143338023-5bdf607d-a572-4d7f-b1e7-8a672800a1e5.png">

**Comment by jiywang3** [comment]
It's fixed! Thanks!

**Comment by digitalbio** [comment]
confirmed.  Thank you!
