### ISSUE TITLE
Unable to remove membrane objects

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#74]
Structure:  1LQQ

1.  This structure should not show membrane objects, but it does.  It is not a membrane protein.
 
2.  I clicked Toggle Membrane to hide them.
 
3. They are still visible.

4.  I am getting questions & complaints about these from students.

Here are the commands:
> load mmdb 1lqq | parameters &mmdbid=1lqq
> toggle membrane
> toggle membrane
> toggle membrane
> 

<img width="716" alt="Screen Shot 2021-11-27 at 10 52 33 AM" src="https://user-images.githubusercontent.com/6663433/143718788-1450e4c8-d58b-4475-b664-0725fe8cb4c7.png">

**Comment by jiywang3** [comment]
This bug was introduced when we use Preferences for membranes. It's fixed. Thanks!
