### ISSUE TITLE
Cysteine disulfide bonds always visible

### ISSUE THREAD

**Issue by OtimusOne** [ncbi/icn3d#77]
Hello, I've noticed that the disulfide bonds are always drawn no matter what representation is selected and they remain visible even after selecting Menu->Style->Proteins->Hide.
https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?pdbid=1brq
https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?mmdbid=3nq3

![icn3d](https://user-images.githubusercontent.com/24881451/157329715-c971591c-8c7c-4024-ae1e-ded1ca0912cf.png)

**Comment by jiywang3** [comment]
Thanks for your bug report. Now the disulfide bonds will be hidden if you choose "Style > Proteins > Hide". The proper way to hide/show disulfide bonds is to use the menu "Analysis > Disulfide Bonds".

**Comment by OtimusOne** [comment]
> Thanks for your bug report. Now the disulfide bonds will be hidden if you choose "Style > Proteins > Hide". The proper way to hide/show disulfide bonds is to use the menu "Analysis > Disulfide Bonds".

So I've noticed something else, for this example https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?pdbid=1brq "Analysis > Disulfide Bonds > Hide" works but then if I try "Analysis > Disulfide Bonds > Show" it doesn't do anything.

However for this example https://www.ncbi.nlm.nih.gov/Structure/icn3d/full.html?mmdbid=3nq3 Hide/Show works fine.

**Comment by jiywang3** [comment]
Could you refresh your browser so that the iCn3D version is 3.10.1 by clicking the menu "Help > About iCn3D"? This new version should have fixed it.

**Comment by OtimusOne** [comment]
> Could you refresh your browser so that the iCn3D version is 3.10.1 by clicking the menu "Help > About iCn3D"? This new version should have fixed it.

Yeah, thank you.
One last thing about these bonds, they look a bit out of place using the Lines representation, perhaps a line style could be implemented for them as well.

![icn3d2](https://user-images.githubusercontent.com/24881451/157558167-91ddf97d-3fc4-4e6d-a639-cd127b74fa3b.png)
.
