### ISSUE TITLE
Unable to select and highlight domain in aligned structures

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#79]
1.  Aligned two PDB structures - 6VXX and 6VSB
2. Used the A key to alternate.
3. Clicked Analysis > Seq & Annotations
4. Clicked the receptor binding domain.  

The domain title would appear but I was unable to highlight the domain. I tried this with all the different chains.  

https://structure.ncbi.nlm.nih.gov/icn3d/share.html?7roBXLBZKxk6FBeX7

**Comment by jiywang3** [comment]
It seemed working for me. 
![image](https://user-images.githubusercontent.com/11690222/167254945-53188daf-4462-438b-bc18-8002383fc013.png)

**Comment by jiywang3** [comment]
The bug was there. I just fixed it.
