### ISSUE TITLE
2D representations of Secondary structures and topologies

### ISSUE THREAD

**Issue by youkha** [ncbi/icn3d#8]
Having selected for example 1 or 2 domains/chains one may want to drill down at the SSEs level 
If showing interactions then a Schematics 3D representation can be highligted as in the sequence window but also in the 2D window as a topological representation

**Comment by jiywang3** [comment]
Yes, I will improve the 2D interaction display to show only the selected chains.

**Comment by jiywang3** [comment]
This is implemented in the new version iCn3D 2.0.0.
