### ISSUE TITLE
selecting sugars and other chemicals

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#83]
This is a feature request.

It would be really nice to be able to click the name of a sugar or other chemical and select all those sugars at once.   What happens instead is that clicking the name or the image sends to the user to PubChem and doesn't select anything.  This disrupts your work and is frustrating to users.

Here's an example of a structure where we could this:  1HZH  - you would click BMA for example and all the molecules of B-mannose would be highlighted.

**Comment by jiywang3** [comment]
That's a good suggestion and will make the UI more consistent. I just added the feature. Please try it out.
