### ISSUE TITLE
Could we apply a "lock" to keep something hidden?

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#85]
Sometimes I use View Selected to hide the unselected part of a structure.

Then I do something and the unselected part reappears.

Could we have a Lock or something so I could keep the unselected part hidden unless I choose to show it? 

This would be really helpful for teaching and annotations.

**Comment by jiywang3** [comment]
When no atoms are selected, iCn3D shows all atoms as if all atoms are selected. That's probably what you saw. I can change the behavior to show all previously displayed atoms when no atoms are selected.
