### ISSUE TITLE
Viewing predicted mutations in aligned structures

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#86]
I have kind of a complicated question / feature request.

I have two aligned structures: 6LR7 and 2H5Q.  6LR7 contains an antibody bound to GFP.  2H5Q is another fluorescent protein (mCherry)

I would like to see if I can predict how mutations in the antibody (6LR7_B) might impact binding to 2H5Q.  But when I make a "mutation" in 6LR7_B, a new window appears and 2H5Q disappears. 

Is there a way to predicted mutations in the antibody that binds GFP (6LR7_A) and see how that might impact binding to 2H5Q?

**Comment by digitalbio** [comment]
Here's a link to the structure before I tried using the Mutation feature.

**Comment by jiywang3** [comment]
We don't allow interactions between two structures with different PDB IDs. What you can do is to select 6LR7_B and 2H5Q_A, click "View Selection" to view these two chains, then output them as a single PDB, and remove all headers in the PDB file. 

I need to add a feature to do mutation analysis for any custom PDB. Then you can analyze the mutation for your generated PDB.

**Comment by jiywang3** [comment]
I just released iCn3D 3.14.1. If you click the menu "Analysis > Mutation", you will see the option for "Show Mutation in". Please choose "Current Page" to load the mutation for the currently loaded structure.
