### ISSUE TITLE
Open AlphaFold PAE file with latest result file

### ISSUE THREAD

**Issue by danny2551515** [ncbi/icn3d#88]
Hello,

I am using iCn3D to check PDB files predicted with AlphaFold.
While using iCn3D features to check PAE, I encountered a problem:
According to the AlphaFold v.2.2.3 log, the format of Colab PAE json output changed.

When attempting to use the json file result from the latest version of AlphaFold Colab to open PAE, I receive the following message: 'The PAE file didn't have the right format....', and it is not possible to check PAE.

Using the results from locally installed AlphaFold, attempting to use PKL file to open PAE results in PAE not being printed after file load.

Is there a way to address these problems?

Thank you.

**Comment by jiywang3** [comment]
Thank you for your bug report. The issue was fixed in our dev version. We'll release it tomorrow evening.

**Comment by jiywang3** [comment]
iCn3D 3.17.0 was released. It should be working now.
