### ISSUE TITLE
Chemical display isn't right

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#90]
The peroxide in 3ABM should show two oxygens.  

The first image shows how it looks in Molecule World. This is how it should look. You should be able to see both of the oxygen atoms. The second image shows how it looks in iCn3D.  I tried selecting Style > Chemicals > Ball & Stick but I can't get the display to show the two oxygens.

 
![MoleculeWorld_peroxide](https://user-images.githubusercontent.com/6663433/198845934-bb609ce8-d7a5-4f43-97fa-178bf73311e8.JPG)

<img width="1018" alt="iCn3D peroxide" src="https://user-images.githubusercontent.com/6663433/198846065-b884e44c-6856-4bf1-87cd-bee4c6ff44aa.png">

**Comment by digitalbio** [comment]
There are other odd things about this structure, too. 
1. Only single heme, Copper, and peroxide groups are shown in annotation info. This makes it hard to select them from the Annotations window.  
2.  One of them shows the peroxide in the structure window and the other doesn't. 
3.  Can we do something about that weird green tube?  Can we make it thinner - so the atoms are easier to see?

 <img width="1397" alt="3ABM_iCn3D" src="https://user-images.githubusercontent.com/6663433/198846626-5087329a-9ae6-4c1a-b93e-ded90b7a1b62.png">

**Comment by digitalbio** [comment]
I'm adding this image because it has the same problem.  You can see that the nitrogen is not being displayed with the ball shape. 
<img width="751" alt="3AG4" src="https://user-images.githubusercontent.com/6663433/198846997-db539eed-4501-4628-b28a-1da88bc0e77c.png">

**Comment by digitalbio** [comment]
I should have added - I was using Firefox.  There is an additional problem if I use Chrome.  I'm that issue separately.

**Comment by jiywang3** [comment]
You can try the following as shown in the sharable link https://structure.ncbi.nlm.nih.gov/icn3d/share.html?x6YEtAiPGt8kny299 and image below. First, open the preference in the menu "Style > Preference" to change the stick radius from 0.4 to 0.2. Second, change chemical style to "Ball and Stick", and change ions style to "dot". In the "Sequence & Annotations" window, click the tab "Details" to show both "PER" and "CU" residues as shown in the image. I just showed the residues 4 angstrom away from the "PER" residues.
![image](https://user-images.githubusercontent.com/11690222/198851867-be81e63c-146c-4aaf-8460-62f00950151b.png)

**Comment by digitalbio** [comment]
The width of the sticks aren't a problem, it's the width of this green tube.  I would to change that width without changing the width of the sticks. I don't see an option for doing that.

<img width="467" alt="green tube" src="https://user-images.githubusercontent.com/6663433/198854221-ee658b18-ba03-41ef-8bc8-46713c5af9f1.png">

**Comment by jiywang3** [comment]
The green bonds are cross-linkages and they are real bonds between residues. Currently we don't separate them from other bonds yet.

**Comment by jiywang3** [comment]
Now you can adjust the thickness of the "cross-linkage" bonds in the menu "Style > Preferences: Cross-Linkage Radius". Thanks!
