### ISSUE TITLE
Unable to show selected chemicals when using Chrome

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#91]
Browser - Chrome on Mac

1. I opened 1OCC and selected all the chemicals.
2. I chose View > View Selection

I expected that the chemicals would be displayed and the proteins would be hidden.  That's what happens on Firefox.  

Instead, the proteins were not hidden.

**Comment by jiywang3** [comment]
You can select chemicals by clicking the menu "Analysis > Defined Sets" and then clicking "Chemicals" in the "Defined Sets". Then you can click "View > Selection" to view the chemicals only. Here is the sharable URL: https://structure.ncbi.nlm.nih.gov/icn3d/share.html?AvTnRYW3F5Suavjn8. If you simply select on 3D, you need to hold the "Alt" key to select the first selection, then hold the "Ctrl" key to add more to the selection. If you use "Ctrl" key for the first set, it will add your selection to the default set, which contains all residues.

**Comment by digitalbio** [comment]
This is helpful, and it's nice to have workarounds but I think selecting items in the Annotation window should also work.

**Comment by jiywang3** [comment]
Yes, you can also select from the Annotation window. Again, don't use the ctrl key at the beginning. If you can be more specific about the steps you went through, I may be able to reproduce your problem.
