### ISSUE TITLE
Customize menus doesn't work as expected

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#92]
I opened customize menus.  All the items were checked so I unchecked the things that I wanted to hide.

When I loaded my preferences, all the items that were checked disappeared from the menus and the unchecked items were all displayed.  

The preferences file is attached. 
[icn3d_shown_menus.txt](https://github.com/ncbi/icn3d/files/9894682/icn3d_shown_menus.txt)

**Comment by jiywang3** [comment]
That's a bug. Previously we tried to save the shown menus. Then we switched to save the hidden menus since this way new menus will show up for any pre-existing menu files. I will fix it next week.

**Comment by digitalbio** [comment]
Thanks!
