### ISSUE TITLE
Is there a command or function that can enable to display PAE map?

### ISSUE THREAD

**Issue by danny2551515** [ncbi/icn3d#94]
Hello,

We would like to include iCn3D in our lab’s web server and then check alphafold’s prediction result structures. Following the iCn3D page’s guide, we set up alphafold’s prediction to automatically display its results. We would like to simultaneously show PAE map when using iCn3D to show alphafold prediction results. Is there a command or function that can enable to display PAE map automatically through specific PAE File in the server without uploading files through File > Open File > AlphaFold PAE File?

Thank you.

**Comment by jiywang3** [comment]
We will add this function to load PAE files from your server.

**Comment by jiywang3** [comment]
Now you can load a PAE json file with a URL, e.g., https://www.ncbi.nlm.nih.gov/Structure/icn3d/?type=pae&url=https://alphafold.ebi.ac.uk/files/AF-Q76EI6-F1-predicted_aligned_error_v4.json
