### ISSUE TITLE
The hydrophocity legend should contain information about hydrophobicity

### ISSUE THREAD

**Issue by digitalbio** [ncbi/icn3d#98]
The legend for hydrophobicity should show a color key that shows how the color corresponds to the hydrophobicity. 

It should be something like this:

Dark green = Most hydrophobic
Light green = hydrophobic
White  = polar, not hydrophobic
Grey = charged, not hydrophobic

<img width="515" alt="Screenshot 2022-11-15 at 1 12 39 PM" src="https://user-images.githubusercontent.com/6663433/202026340-577fc67a-9c8a-4851-a82b-1fdc3ed1ba8b.png">

Also - the legend shown above has Uracil spelled incorrectly.  It should not have an "e" on the end.

**Comment by jiywang3** [comment]
Thanks for your report. We just released iCn3D 3.19.0 to fix it.
